baseURL: "https://glasshomestudio.com/"
title: "Glass Home Studio - Stained Glass - Buckeye, AZ"
paginate: 6
theme: PaperMod
pluralizelisttitles: "false"

module:
  mounts:
  - source: static
    target: assets

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Glass Home Studio - Stained Glass in Buckeye, AZ"
  description: "Glass Home Studio offers custom-made stained glass art at affordable prices, with 40+ years experience.  Based in Buckeye, AZ and serving Phoenix area."
  author: Richard Knobloch
  images: ["/img/flower-closeup.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  label:
    text: "Glass Home Studio"

  assets:
    disableHLJS: true
    # disableFingerprinting: true
    favicon: "https://glasshomestudio.com/img/favicon/logo-32x32.ico"
    favicon16x16: "https://glasshomestudio.com/img/favicon/logo-16x16.ico"
    favicon32x32: "https://glasshomestudio.com/img/favicon/logo-32x32.ico"
    apple_touch_icon: "https://glasshomestudio.com/img/favicon/logo-57x57.ico"
    #safari_pinned_tab: "<link / abs url>"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome to Glass Home Studio"
    subtitle: "Custom-made stained glass art at affordable prices"
    imageUrl: "img/flower-closeup.png"
    imageWidth: 240
    imageHeight: 240
    imageTitle: "Glass Home Studio"
    buttons:
      - name: Portfolio
        url: portfolio
      - name: Contact
        url: contact

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: process
      name: process
      url: /process/
      weight: 15
    - identifier: portfolio
      name: portfolio
      url: /portfolio/
      weight: 20
    - identifier: contact
      name: contact
      url: /contact/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true